config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  devise_for :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'
  get 'posts/:id/download', to: 'posts#download', as: 'download_post'
  get 'pages/media'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness:  {scope: :post_id }  
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video

  acts_as_punchable
  belongs_to :user

  has_many :likes
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes

  def likes?(post)
    likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    if !@like.save
      flash[:alert] = "Yor already liked this"
    end
    # redirect to the liked post
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def media
    if user_signed_in?
      @posts = current_user.posts
  
      if @posts.empty?
        @message = "You have no posts yet."
      else
        @message = "Your posts:"
      end

    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.punch(request)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def download
    set_post
    send_data @post.video.download, filename: @post.video.filename.to_s
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    return unless @post.user_id == current_user.id

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    return unless @post.user_id == current_user.id

    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :image, :video, :user_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/_footer.html.erb
<!-- component -->
<!-- Foooter -->
<footer class="" style="background-color: #282828;    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  position: fixed;
  left: 0;
  bottom: 0; width: 100%;">
  <div class="max-w-screen-xl px-4 py-4 mx-auto space-y-1 overflow-hidden sm:px-6 lg:px-8"  >
    <nav class="flex flex-wrap justify-center -mx-5 -my-2">
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          About
        </a>
      </div>
      <div class="px-5 py-2">
        <a href="#" class="text-base leading-6 text-white hover:text-gray-200">
          Blog
        </a>
      </div>
      <%# if current_user %>
      <div class="px-5 py-2">
        <%#= link_to "Account details", edit_user_registration_path, class:"text-base leading-6 text-white hover:text-gray-200" %>
      </div>
      <%# end %>
    </nav>
    <p class="mt-8 text-base leading-6 text-center text-gray-400">
      © 2023 My Space Tube - All rights reserved.
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins:wght@500&family=Roboto:wght@500&display=swap" rel="stylesheet">
<!-- component -->
<div class="place-items-center">
  <section class="relative mx-auto">
    <!-- navbar -->
    <nav class="flex items-center justify-between text-white" style="background-color: #282828; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
      <div class="flex items-center w-full px-5 py-6 w-90 xl:px-12">
        <a class="text-3xl font-bold font-heading nav-title" href="/">
          <!-- <img class="h-9" src="logo.png" alt="logo"> -->
          My Space Tube
        </a>
        <!-- Nav Links -->
        <ul class="hidden px-4 mx-auto space-x-12  md:flex font-heading">
          <li><a class="hover:text-gray-200" href="/">Home</a></li>
          <% if current_user %>
            <li><a class="hover:text-gray-200" href="#">  <%= link_to "My Media", pages_media_path %></a></li> 
            <li><a class="hover:text-gray-200" href="<%= new_post_path %>">Upload</a></li>
            <%= button_to("Log Out", destroy_user_session_path, method: :delete) %></li>
          <% else %>
            <li><a class="hover:text-gray-200" href="#">  <%= link_to "Sign up", new_user_registration_path %></a></li>
            <li><%= link_to "Login", new_user_session_path, class:"bg-white hover:bg-gray-100 text-gray-800 py-2 px-4 border border-gray-400 rounded shadow" %></a></li>

          <% end %>
        </ul>
        <!-- Header Icons -->
      </div>
      <!-- Responsive navbar -->
      <%#= render "layouts/search_bar"%>
    </nav>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySpaceTube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container px=5 mx-auto mt-13">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/like_params.html.erb
<h1>Likes#like_params</h1>
<p>Find me in app/views/likes/like_params.html.erb</p>

app/views/pages/media.html.erb
<div class="container mt-24 px-24">
  <h6 class="block mb-5 text-5xl">
    <%= @message%>
  </h6>
  <%= link_to 'Upload', new_post_path, class: "bg-black hover:bg-gray-500 text-white  py-2 px-4 rounded inline-flex items-center " %>
  <br>
  <br>
  <% if current_user %>   
    <div id="posts" class="min-w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
      <%= render @posts %>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", rows: 5 %>
  </div>
  <div class="my-5">
    <%= form.label :video %>
    <%= form.file_field :video, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", accept: "video/*" %>
  </div>
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id %>
    <%# <p>  By continuing you agree to our 
    <%= link_to "Terms of Use", pages_tos_path, style:"color: blue;" %> 
  <div class="inline">
    <%= form.submit "Upload Video", class: "rounded-lg py-3 px-5 bg-blue-600 text-white mt-2 inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="youtube-layout relative">

  <% if post.image.attached? %>
<%= image_tag(post.image, quality: 10)%>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to post, class: "overlay flex items-center justify-center opacity-0 transition-opacity duration-300" do %>
      <div class="overlay-content text-center">
        <h2 class="post-title text-2xl text-white leading-tight mb-2"><%= post.title %></h2>
        <p class="text-white post-details text-sm">
          <%#= post.user.email %>
          <br>
          <%= time_ago_in_words(post.created_at) %> ago
        </p>
      </div>
    <% end %>
  <% end %>
</div>

<style>
.youtube-layout {
  position: relative;
  width: 100%;
  height: 200px;
  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  display: inline-block;
  overflow: hidden;
  padding: 12px;  
}

.thumbnail {
  display: block;
  max-width: 100%;
  max-height: 100%;
  width: 100%;
  height: 100%;
  object-fit: cover;  
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  transition: opacity 0.3s;
}

.youtube-layout:hover .overlay {
  opacity: 1;
}

.overlay::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: radial-gradient(ellipse at center, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, .35) 20%);
  pointer-events: none;
}

.post-title {

  color: white;
  position: absolute;
  z-index: 300;
  top: 16px;
  left: 16px;
}

.post-details {
  color: white;
    z-index: 300;
  position: absolute;
  bottom: 16px;
  left: 16px;
}

/* Responsive changes */
@media screen and (max-width: 768px) {
  .youtube-layout {
    width: 100%;
  }
}


</style>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="row container mx-auto mt-12">
<%# <%= search_form_for @q do |f| %> 

<h1 class="text-3xl font-bold mb-4">
  Stunning royalty-free images & videos
</h1>
<h2 class="text-lg text-gray-600">
Download high quality stock images, videos shared by our community.

<br>
  <%# <% end %> 
  <div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex items-center justify-between">
    <%#= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="posts" class="min-w-full grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= render "form", post: @post %>
  <%#= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

<div class="grid lg:grid-cols-2 grid-cols-1 mt-4 px-4">
  <div class="youtube-layout">
    <% if @post.video.attached? %>
      <div class="video-container">
        <video controls>
          <source src="<%= url_for(@post.video) %>" type="video/mp4">          
          Your browser does not support the video tag.          
        </video>        
      </div>
      <h2 class="text-1xl post-details"> Uploaded <%= time_ago_in_words(@post.created_at) %> ago</h2>
    <% else %>
      <% if @post.image.attached? %>
        <%= image_tag(@post.image, class: "thumbnail") %>
      <% end %>
    <% end %>
  </div>

  <div class="overlay xl:text-align:left;  ">
    <div class="overlay-content">
      <h2 class="text-3xl post-details"><%= @post.title %></h2>
      <h2 class="text-2xl post-details"><%= @post.hits %> views </h2>
      <p class="post-details">
       Posted by <%= @post.user.email %>
      </p>
    </div>
    <br>
  <div class="button-container">
    <% if @post.video.attached? || @post.image.attached? %>
      <%= link_to 'Download', download_post_path(@post), class: " font-medium button-style" %>      
    <% end %>
    <% if current_user %> 
      <%# <%= button_to "like", likes_path, params: {like: {post_id: @post.id}}, method: :post %>    
      <%# <% @post.likes.count %>  

      <% if current_user.likes?(@post) %>
        <% unlike_button = button_to image_tag("heart-icon.svg", style:"height: 20px;"), like_path(@post.likes.find_by(user_id: current_user)), method: :delete, class:" inline-block font-medium button-style" %>
        <%= unlike_button %>
      <% else %>
        <% like_button = button_to image_tag("heart.svg", style:"height: 20px;"), likes_path, params: { like: { post_id: @post.id } }, method: :post, class:" inline-block font-medium button-style" %>
        <%= like_button %>
      <% end %>
      <h2 class="text-1xl post-details"> Likes: <%= @post.likes.count %> </h2> 

      <% if @post.user_id == current_user.id %>       
          <%= link_to image_tag("edit.svg", style:"height: 20px;"), edit_post_path(@post), class: " inline-block button-style edit-button" %>
          <%= button_to image_tag("delete.svg", style:"height: 20px;"), post_path(@post), method: :delete, class: " font-medium button-style" %>
      <% end %> 
    <% end %>
  </div>
</div>
<style>

  .youtube-layout {
  width: 65%;
  margin: 0 auto;
  }

  .thumbnail {
   display: block;
   max-width: 100%;
   max-height: 100%;
   width: auto;
   height: auto;
   margin: 0 auto;
   object-fit: contain;
  }

  .post-details {
  padding: 10px;
  }

  .post-title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 8px;
  }

  .post-details p {
  font-size: 14px;
  }     
  
  .video-container {
      position: relative;
      padding-bottom: 56.25%; /* 16:9 aspect ratio (change as needed) */
      padding-top: 30px;
      height: 0;
      overflow: hidden;
    }

  .video-container video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  .button-container {
    display: flex;
    align-items: center;
    padding-left: 12px;
  }

  .button-style {
    display: inline-block;
    margin-right: 10px; /* Adjust as needed for spacing between buttons */
    padding: 0 15px;
    text-align: center;
    text-decoration: none;
    color: #fff;
    background-color: #A9A9A9;
    border: none;
    border-radius: 5px;
    height: 40px; /* Adjust the height as needed */
    line-height: 40px; /* Match the height for vertical alignment */
  }

  /* Adjustments for button styles on hover, focus, etc. */
  .button-style:hover,
  .button-style:focus {
    background-color: #555;
    /* Additional styles for hover/focus state */
  }

  .edit-button {
   padding-top: 10px;
  }
</style>